[package]
name = "audio_painter"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "make audio out of other audio"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
hound = "3.5.1"
indicatif = "0.17.8"
itertools = "0.13.0"
